// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: prairie/plugin/v1/scheduled_task.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunScheduledTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskKey       string                 `protobuf:"bytes,1,opt,name=task_key,json=taskKey,proto3" json:"task_key,omitempty"`
	Input         *structpb.Struct       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunScheduledTaskRequest) Reset() {
	*x = RunScheduledTaskRequest{}
	mi := &file_prairie_plugin_v1_scheduled_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScheduledTaskRequest) ProtoMessage() {}

func (x *RunScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prairie_plugin_v1_scheduled_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*RunScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_prairie_plugin_v1_scheduled_task_proto_rawDescGZIP(), []int{0}
}

func (x *RunScheduledTaskRequest) GetTaskKey() string {
	if x != nil {
		return x.TaskKey
	}
	return ""
}

func (x *RunScheduledTaskRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

type RunScheduledTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *structpb.Struct       `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunScheduledTaskResponse) Reset() {
	*x = RunScheduledTaskResponse{}
	mi := &file_prairie_plugin_v1_scheduled_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScheduledTaskResponse) ProtoMessage() {}

func (x *RunScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prairie_plugin_v1_scheduled_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*RunScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_prairie_plugin_v1_scheduled_task_proto_rawDescGZIP(), []int{1}
}

func (x *RunScheduledTaskResponse) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_prairie_plugin_v1_scheduled_task_proto protoreflect.FileDescriptor

const file_prairie_plugin_v1_scheduled_task_proto_rawDesc = "" +
	"\n" +
	"&prairie/plugin/v1/scheduled_task.proto\x12\x11prairie.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"c\n" +
	"\x17RunScheduledTaskRequest\x12\x19\n" +
	"\btask_key\x18\x01 \x01(\tR\ataskKey\x12-\n" +
	"\x05input\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05input\"K\n" +
	"\x18RunScheduledTaskResponse\x12/\n" +
	"\x06output\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06output2o\n" +
	"\rScheduledTask\x12^\n" +
	"\x03Run\x12*.prairie.plugin.v1.RunScheduledTaskRequest\x1a+.prairie.plugin.v1.RunScheduledTaskResponseBYZWgithub.com/prairie-server/prairie-plugin-sdk/pkg/pluginproto/prairie/plugin/v1;pluginv1b\x06proto3"

var (
	file_prairie_plugin_v1_scheduled_task_proto_rawDescOnce sync.Once
	file_prairie_plugin_v1_scheduled_task_proto_rawDescData []byte
)

func file_prairie_plugin_v1_scheduled_task_proto_rawDescGZIP() []byte {
	file_prairie_plugin_v1_scheduled_task_proto_rawDescOnce.Do(func() {
		file_prairie_plugin_v1_scheduled_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prairie_plugin_v1_scheduled_task_proto_rawDesc), len(file_prairie_plugin_v1_scheduled_task_proto_rawDesc)))
	})
	return file_prairie_plugin_v1_scheduled_task_proto_rawDescData
}

var file_prairie_plugin_v1_scheduled_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prairie_plugin_v1_scheduled_task_proto_goTypes = []any{
	(*RunScheduledTaskRequest)(nil),  // 0: prairie.plugin.v1.RunScheduledTaskRequest
	(*RunScheduledTaskResponse)(nil), // 1: prairie.plugin.v1.RunScheduledTaskResponse
	(*structpb.Struct)(nil),          // 2: google.protobuf.Struct
}
var file_prairie_plugin_v1_scheduled_task_proto_depIdxs = []int32{
	2, // 0: prairie.plugin.v1.RunScheduledTaskRequest.input:type_name -> google.protobuf.Struct
	2, // 1: prairie.plugin.v1.RunScheduledTaskResponse.output:type_name -> google.protobuf.Struct
	0, // 2: prairie.plugin.v1.ScheduledTask.Run:input_type -> prairie.plugin.v1.RunScheduledTaskRequest
	1, // 3: prairie.plugin.v1.ScheduledTask.Run:output_type -> prairie.plugin.v1.RunScheduledTaskResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_prairie_plugin_v1_scheduled_task_proto_init() }
func file_prairie_plugin_v1_scheduled_task_proto_init() {
	if File_prairie_plugin_v1_scheduled_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prairie_plugin_v1_scheduled_task_proto_rawDesc), len(file_prairie_plugin_v1_scheduled_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prairie_plugin_v1_scheduled_task_proto_goTypes,
		DependencyIndexes: file_prairie_plugin_v1_scheduled_task_proto_depIdxs,
		MessageInfos:      file_prairie_plugin_v1_scheduled_task_proto_msgTypes,
	}.Build()
	File_prairie_plugin_v1_scheduled_task_proto = out.File
	file_prairie_plugin_v1_scheduled_task_proto_goTypes = nil
	file_prairie_plugin_v1_scheduled_task_proto_depIdxs = nil
}
